name: veryminimalist
description: "Make your Android phone very minimalist."
publish_to: 'none'
version: 1.0.0+1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_device_apps: ^0.6.0
  package_info_plus: ^10.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF Pro.otf